### ISSUE TITLE
Making the UV-Pass usable for the Map-UV-Node.

### ISSUE THREAD

**Issue by hansnolte** [LuxCoreRender/LuxCore#96] opened 2018-04-19 12:47 UTC
The Luxcore UV-Pass does not work with the Map-UV-Node in the Blender-Compositor
Please make it usable for the Map-UV-Node?

Blender Thread:
https://blenderartists.org/forum/showthread.php?448186-LuxCoreRender-2-0&p=3303671&viewfull=1#post3303671

![picture-1](https://user-images.githubusercontent.com/7922627/38992236-6e903c7a-43e0-11e8-9c48-0d423fd1050a.jpg)

![picture-2](https://user-images.githubusercontent.com/7922627/38992246-786d22e4-43e0-11e8-89fd-6d9826f896b5.jpg)

**Comment by Theverat** [comment] 2018-04-19 13:25
It looks like Cycles puts "1.0" into the third channel (blue) of the UV pass.
However it only does so where a UV mapping exists (at least I assume that).

I think we can replicate this behaviour in pyluxcoreforblender, so we don't have to touch LuxCore's AOVs directly.

You can also do it with the following node setup in Blender's compositor:
![scrn_2018-04-19_15-23-45](https://user-images.githubusercontent.com/1584761/38994184-ebeafc1e-43e5-11e8-8394-989b8a437118.png)

**Comment by Dade916** [comment] 2018-04-19 15:12
It is like if the last value is a mask of where UV values are present or not, right ? It may be handy to avoid the ambiguous case where you don't know if the UV(0.0, 0.0) is there because there is no UV or there is an UV value of (0.0, 0.0).
"Wasting" 50% memory to avoid this ambiguity is a bit expansive (we could just use a special value like INF) but it isn't a big deal. We can add the additional mask channel if you want.

**Comment by Theverat** [comment] 2018-04-19 15:17
I have committed a change concerning this issue: 651be1478d18994488c8079baff958f470edd153

> "Wasting" 50% memory to avoid this ambiguity is a bit expansive (we could just use a special value like INF) but it isn't a big deal. We can add the additional mask channel if you want.

We have to think of other programs reading our AOVs besides Blender, too.
I would not introduce special values like INF for this reason.
And wasting the memory is also unnecessary in my opinion.

I would just ignore the special edge case of UV(0, 0).

Besides, the UV channel in LuxCore has the limitation (from Blender point of view) that it is not anti-aliased.
So if a user wants to do extensive compositing with it, he will need to render an additional aliased mask channel anyway (like BY_MATERIAL_ID).
He can then use this mask channel as the third channel and combine everything with Blender's compositor nodes (combine RGB).

**Comment by hansnolte** [comment] 2018-04-19 16:00
Hi Theverat,

great workaround.

I am currently doing something with the MATERIAL_ID.

As in Cycles, I also have a color border and in the picture I put over it,
the font looks pretty jaggy.

_"He can then use this mask channel as the third channel and combine everything with Blender's compositor nodes (combine RGB)."_
Can you please give me an Example.

Many greetings
Hans



![original](https://user-images.githubusercontent.com/7922627/39003528-52414828-43fb-11e8-860e-3858a8cff0fa.jpg)

![composit](https://user-images.githubusercontent.com/7922627/39003549-5b3906e6-43fb-11e8-99f9-de5d19b1ef39.jpg)

**Comment by Theverat** [comment] 2018-04-19 17:15
> "He can then use this mask channel as the third channel and combine everything with Blender's compositor nodes (combine RGB)."
Can you please give me an Example.

You would need the [MATERIAL_ID_MASK](http://www.luxrender.net/wiki/Render_passes#MATERIAL_ID_MASK) AOV, which is anti-aliased.
But it is not yet possible because the needed AOV (pass) is not yet available in BlendLuxCore.

The jaggy font in your example is probably caused by the fact that the UV AOV in LuxCore is not anti-aliased.
Most AOV-based compositing techniques have the problem that many AOVs are not anti-aliased because it would make the values meaningless (you can't anti-alias an ID, either a pixel refers to object A or object B).

There are solutions for this, like "Deepmatte", but not yet available in LuxCore (or Cycles, as far as I know).
So the current workaround is to oversample: render the image twice as large, do your compositing, then scale the output down.

**Comment by hansnolte** [comment] 2018-04-20 07:25
Thank you for the detailed explanation.

Rendering in double resolution in Luxcore without Denoiser (should only come in 2.1) is of course not so great.

Many greetings
Hans

**Comment by Theverat** [comment] 2018-04-20 08:04
You will only need 1/4th of the samples to get the same noise level if you double the resolution and intend to downscale in the end.

**Comment by hansnolte** [comment] 2018-04-20 08:17
Hi Theverat,

I just tested it with Cycles.
2560x1440 scaled down to 1280x720.
And it still looks terrible.
![double-resolution](https://user-images.githubusercontent.com/7922627/39038530-0bb28758-4484-11e8-940b-c05e933f7bb3.jpg)

**Comment by Theverat** [comment] 2018-04-20 10:43
If the problem is not LuxCore-related, you should probably ask the question on a Blender-related platform, e.g. https://blender.stackexchange.com/

**Comment by Theverat** [comment] 2018-04-25 15:52
Since the UV AOV now looks like Blender expects it to be, I think we can close this issue.

**Closed** 2018-04-26 08:37 UTC
Labels: enhancement, question
