### ISSUE TITLE
[GPU] Layering Materials not fully working.

### ISSUE THREAD

**Issue by mjutrzenka** [LuxCoreRender/LuxCore#319] opened 2020-03-28 01:30 UTC
![image](https://user-images.githubusercontent.com/36268269/77811460-b9a38f80-709a-11ea-9aae-7db13216e157.png)

So this is how image looks when u just render it with simple single node material.. 

![image](https://user-images.githubusercontent.com/36268269/77811487-f079a580-709a-11ea-8fe7-19f4db87372f.png)

This is where bug starts as u can see we no longer see the metal material it is just the 2nd material. this is rendered on GPU

![image](https://user-images.githubusercontent.com/36268269/77811531-3a628b80-709b-11ea-901c-c9f1782d9871.png)

And this is the correct render done on CPU

**Comment by mjutrzenka** [comment] 2020-04-04 00:42
so this is file that u can render in 30 sec and it shows the issiue.. it autimaticly renders 1 render on CPU and 1 on GPU and shows both next to each other.
[bug.zip](https://github.com/LuxCoreRender/LuxCore/files/4430498/bug.zip)

**Comment by Dade916** [comment] 2020-04-08 10:17
This is a duplicate of #307. So it is known limitation.

Both Mix and GlossyCoatting (all materials that can reference other materials) supports only directly plugged bump mapping, they will ignore the bump mapping of all sub-nodes.

As simple workaround, you can just plug the bump map directly in GlossyCoatting node, instead of the metal sub-node, and it will work on GPU too:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/78772507-20298700-7992-11ea-83d3-22752b4f4acc.png)

@Theverat , until when #307 is not fixed, we could add a warning in BlendLuxCore if someone use bump mapping on a glossycoatting/mix sub-node.

**Comment by Dade916** [comment] 2020-04-08 10:18
This is a duplicate of #307.

**Closed by Dade916** 2020-04-08 10:18 UTC
Labels: known_bug

**Comment by mjutrzenka** [comment] 2020-04-08 13:33
> This is a duplicate of #307. So it is known limitation.
> 
> Both Mix and GlossyCoatting (all materials that can reference other materials) supports only directly plugged bump mapping, they will ignore the bump mapping of all sub-nodes.
> 
> As simple workaround, you can just plug the bump map directly in GlossyCoatting node, instead of the metal sub-node, and it will work on GPU too:
> 
> ![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/78772507-20298700-7992-11ea-83d3-22752b4f4acc.png)
> 
> @Theverat , until when #307 is not fixed, we could add a warning in BlendLuxCore if someone use bump mapping on a glossycoatting/mix sub-node.

no this is not the workaround!!! as u can see the both shaders have bump map.. the base.. and the clearcoat... have bump in such situation! with is tottaly not the effect u want..

**Comment by Dade916** [comment] 2020-04-10 13:36
Check the latest news on issue #307.
