### ISSUE TITLE
[bug] open cl rendering constantly crashes.

### ISSUE THREAD

**Issue by matthewv1998** [LuxCoreRender/LuxCore#306] opened 2020-02-28 22:09 UTC
Build 2.3b2. System. 1700x, 2x vega 56, 56gb of ram. 
Issues. Upon building open cl kernel, on any file. There is a near 90% chance it will crash during the build or mid render. These crashes havent happened on cpu. Its on any file. Even the luxcore demo files have crashed/hung.

**Comment by Dade916** [comment] 2020-02-29 13:52
It sounds like  a driver related problem. What operating system are you using ?

You should try to run LuxMark few times and check if it happens with LuxMark too.

**Comment by matthewv1998** [comment] 2020-02-29 21:02
Windows 10, and so far, changing drivers hasnt done much. Is there a version of luxmark that uses the 2.3b2 compiliers? 2.2 is crash free.

**Comment by Dade916** [comment] 2020-03-01 11:27
I assume the problem is something in your setup, software (likely the drivers) or hardware related. LuxMark has been tested for years and it is known to work. If it doesn;t work, the problem is in OS/Drivers/Hardware.

Anyway, the v2.2 works but v2.3b2 crashes, it is a bit different. However there must be something specific of your setup triggering the problem: does it happen even if you use a single GPU ?

**Comment by matthewv1998** [comment] 2020-03-03 07:44
Yeah. 2.2 has no issues what so ever. The 2.3b2 though. Single gpu, 20.2.2, 20.2.1, 19.5.1, all hang at “compiling blender kernals” systems remains responsive and doesnt crash. I dont think its the drivers

**Comment by Dade916** [comment] 2020-03-04 10:04
> Yeah. 2.2 has no issues what so ever. The 2.3b2 though. Single gpu, 20.2.2, 20.2.1, 19.5.1, all hang at “compiling blender kernals” systems remains responsive and doesnt crash. I dont think its the drivers

Are you sure it doesn't hang but takes a very long time to compile (something like 10 minutes) ? Is it the same with any scene ? Including a simple one, like the startup scene with just a cube ?

**Comment by Dade916** [comment] 2020-03-23 10:43
Any progress with the latest version ?

**Comment by matthewv1998** [comment] 2020-03-24 09:57
With the full release it has improved even more, however i tend to have issues with super high poly scenes. (9+mil face things, aka baking stuff) sometimes when rendering that High poly of a scene, it sometimes crashes. it always gets through building open cl kernels now, All crashes I've had have been mid render. I want to say 90%-95% of my renders go through.

Btw, stay safe and healthy.

**Comment by Dade916** [comment] 2020-04-04 15:51
Going to close this one because I doubt we can do anything else.

**Closed by Dade916** 2020-04-04 15:51 UTC
