### ISSUE TITLE
Blender crashes when adding an object like a cube CUDA/OPENCL

### ISSUE THREAD

**Issue by Paulo077** [LuxCoreRender/LuxCore#398] opened 2020-06-22 17:09 UTC
.blend file:  default cube

Steps to reproduce:
1. Switch render engine to LuxCore
1. Switch "Device" to "GPU" (CUDA or OPENCL selected)
1. Select Display Render Preview : Rendered
1. Add cube by MAJ+A / Mesh / Cube
                      => Blender Crash 

Blender It's OK with CPU but crash with OpenCL and CUDA mode

Error message from Blender console:
```
view_update(): checking for changes took 1.0 ms
[Exporter] Update because of: OBJECT | REQUIRES_SCENE_EDIT | VISIBILITY
WARNING: No material defined
[SDL][57.031] Material definition: __CLAY__
[SDL][57.031] Scene objects count: 1
[SDL][57.031] Light definition: 2221296697640
[LuxRays][57.031] Preprocessing DataSet
[LuxRays][57.031] Total vertex count: 48
[LuxRays][57.031] Total triangle count: 24
[LuxRays][57.031] Preprocessing DataSet done
[LuxRays][57.031] Adding DataSet accelerator: MBVH
[LuxRays][57.031] Total vertex count: 48
[LuxRays][57.031] Total triangle count: 24
[LuxRays][57.031] Building Multilevel Bounding Volume Hierarchy: 2 leafs
[LuxRays][57.046] BVH Dataset preprocessing time: 0ms
[LuxRays][57.046] BVH builder: EMBREE_BINNED_SAH
Error   : EXCEPTION_ACCESS_VIOLATION
Ad[LuxRays][57.046] BVH build hierarchy time: 0ms
d[LuxRays][57.046] BVH total build time: 0ms
r[LuxRays][57.046] Total BVH memory usage: 0Kbytes
ess [LuxRays][57.046] BVH Dataset preprocessing time: 0ms
: 0x[LuxRays][57.046] BVH builder: EMBREE_BINNED_SAH
0[LuxRays][57.046] BVH build hierarchy time: 0ms
0[LuxRays][57.046] BVH total build time: 0ms
0[LuxRays][57.046] Total BVH memory usage: 0Kbytes
0[LuxRays][57.046] Building Multilevel Bounding Volume Hierarchy root tree
7[LuxRays][57.046] MBVH root tree builder: EMBREE_BINNED_SAH
F[LuxRays][57.046] MBVH build time: 15ms
F[LuxRays][57.046] Total Multilevel BVH memory usage: 1Kbytes
8[LuxRays][57.046] [Device GeForce GTX 960M CUDAIntersect] MBVH mesh vertices buffer size: 576bytes
EC5CE7D4
Module  : C:\Users\SnakUser\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\bin\pyluxcore.pyd
```

OS: Windows 10
Blender version: 2.83 or 2.90
LuxCore version: 2.4 alpha (lastest built 22/06/2020)

Thanks so much!

**Comment by Dade916** [comment] 2020-06-24 10:23
@Theverat, but is it a BlendLuxCore or LuxCore problem ?

**Comment by Theverat** [comment] 2020-06-24 11:31
I assume it's a LuxCore problem because it's a crash, but I haven't investigated in detail yet.

**Comment by Theverat** [comment] 2020-06-24 11:51
I can also reproduce it on Ubuntu 20.04, with OpenCL backend (CUDA not tested).
Here's a gdb backtrace:
```
(gdb) bt
#0  0x00007fffb15803b9 in clEnqueueNDRangeKernel () at /lib/x86_64-linux-gnu/libOpenCL.so
#1  0x00007fffbee05407 in luxrays::OpenCLDevice::EnqueueKernel(luxrays::HardwareDeviceKernel*, luxrays::HardwareDeviceRange const&, luxrays::HardwareDeviceRange const&)
    (this=0x7fffb2ca4d20, kernel=<optimized out>, globalSize=..., workGroupSize=...) at /home/simon/Projects/LinuxCompile/LuxCore/src/luxrays/devices/ocldevice.cpp:282
#2  0x00007fffbec01bb1 in slg::PathOCLBaseOCLRenderThread::ThreadFilm::ClearFilm(luxrays::HardwareIntersectionDevice*, luxrays::HardwareDeviceKernel*, unsigned long)
    (this=0x7fffa5ba2180, intersectionDevice=0x7fffb2ca4d48, filmClearKernel=0x7fffa5b66730, filmClearWorkGroupSize=<optimized out>) at /home/simon/Projects/LinuxCompile/LuxCore/include/luxrays/core/hardwaredevice.h:37
#3  0x00007fffbeab63cf in slg::TilePathOCLRenderThread::RenderTileWork(slg::TileWork const&, slg::ocl::TilePathSamplerSharedData&, unsigned int) (this=this@entry=
    0x7fffa5b8a300, tileWork=..., sharedData=..., filmIndex=filmIndex@entry=0) at /home/simon/Projects/LinuxCompile/LuxCore/src/slg/engines/tilepathocl/tilepathoclthread.cpp:89
#4  0x00007fffbea8b5a1 in slg::RTPathOCLRenderThread::RenderThreadImpl() (this=0x7fffa5b8a300) at /home/simon/Projects/LinuxCompile/LuxCore/src/slg/engines/rtpathocl/rtpathoclthread.cpp:197
#5  0x00007fffbfab9175 in thread_proxy () at /home/simon/.config/blender/2.83/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#6  0x00007ffff7f87609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff7967103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by Dade916** [comment] 2020-06-25 10:53
This should be a duplicate, now fixed, of https://github.com/LuxCoreRender/LuxCore/issues/399.

**Closed** 2020-06-25 12:49 UTC
Labels: duplicate

**Comment by Paulo077** [comment] 2020-06-26 11:08
I test the lastest build of BlendLuxCore and it's OK with blender 2.83 and 2.90 (bug fix).
Thanks so much for your work !
Have a good day.
