### ISSUE TITLE
pyluxcoretool doesn't support PySide2

### ISSUE THREAD

**Issue by JayFoxRox** [LuxCoreRender/LuxCore#192] opened 2019-04-16 21:06 UTC
Despite #170, the code in pyluxcoretool still depends on the original PySide.

```
$ python3 ../samples/pyluxcoretool/pyluxcoretool.py 
Traceback (most recent call last):
  File "../samples/pyluxcoretool/pyluxcoretool.py", line 44, in <module>
    import pyluxcoretools.pyluxcoremenu.cmd as menuCmd
  File "./lib/pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/cmd.py", line 34, in <module>
    
  File "./lib/pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/menuwindow.py", line 10, in <module>
ModuleNotFoundError: No module named 'PySide'
```

The header of the affected file says:

https://github.com/LuxCoreRender/LuxCore/blob/67e56ff7d27538712adf86ec0ba58d41de1df0e7/src/pyluxcoretools/pyluxcoretools/pyluxcoremenu/menuwindow.py#L3-L10

I did not check if other files could be affected similarily.

I'm not sure how exactly those files are being generated, but those generated files probably shouldn't be part of the LuxCore repository, so that every user generates them locally (from the latest input source files). An exception would be if these are sort-of "baked" generated files: then the header and imports should be modified to suit our needs.

**Comment by acasta69** [comment] 2019-04-17 08:13
The intended behaviour is that, if a PySide or a PySide2 installation is found, files are freshly generated for the found version (see [this](https://github.com/LuxCoreRender/LuxCore/blob/master/cmake/Dependencies.cmake#L53) and [this](https://github.com/LuxCoreRender/LuxCore/blob/master/src/pyluxcoretools/CMakeLists.txt)).

If no PySide nor PySide2 installation is found, then the pre-generated files are used, and those are for PySide. 

At the moment, having no pre-generated files makes the whole build fail if no PySide is found, at least on Windows (it was pointed out in [this thread](https://forums.luxcorerender.org/viewtopic.php?f=4&t=1025)).

**Comment by Dade916** [comment] 2019-04-17 13:53
I assume we can close this one: the explanation is included in Acasta69's comment.

**Closed** 2019-04-17 13:54 UTC
Labels: question

**Comment by JayFoxRox** [comment] 2019-04-17 15:35
The explanation appears to be wrong (or rather: the implementation does something else).

I *do* have pyside2-tools installed; and pyside2-uic is on the path.

---

I investigated this yesterday (but did not report my findings here yet).
This only deletes files for macOS, when it should also delete files for all other platforms (if `PYSIDE_UIC` is available):

https://github.com/LuxCoreRender/LuxCore/blob/master/src/pyluxcoretools/CMakeLists.txt#L37-L45

Wether the files only get deleted if PySide2 is used, or also if PySide is used isn't really relevant.

As I'm on Linux, I'm not affected by the check for `APPLE`, so these files still exist in the repository, and even if `PYSIDE_UIC` is found, the `custom_command` will not be ran, because those files exist already.

Deleting those files from the file tree manually (and rebuilding) works around this issue.

I think the easiest solution is to merge these 2 code blocks (the `APPLE` block and the `PYSIDE_UIC` bock), so the files always get removed / regenerated together. This also avoids the case where the files are deleted, but no tool exists to recreate them.

*Ideally files would not be deleted, but just overwritten automatically. I tried to mess around with `add_custom_target` but I couldn't make it work, so I just gave up on it.*

---

Another thing: Yesterday, I did not notice the pyside-uic code @acasta69 refered to:

https://github.com/LuxCoreRender/LuxCore/blob/2c1ac1ac7d02fd96001c9e474e217d2a5ee3569a/cmake/Dependencies.cmake#L53-L55

But I did find this:

https://github.com/LuxCoreRender/LuxCore/blob/2c1ac1ac7d02fd96001c9e474e217d2a5ee3569a/cmake/SpecializedConfig/Config_OSX.cmake#L26-L30

It looks like the macOS specific search can be removed, if the search path in the generic CMake file is improved.

This was also the reason I didn't report the issue yet: I assumed this was the issue (only macOS checking for `pyside2-uic`); but this doesn't seem to be the case.

---

And one more: When rebuilding, and the pyluxcoretools.zip already exists, then the contents will not be updated, even if the source tree changes. So in order to apply patches, one has to force a rebuild / refresh, or remove the destination zip.

**Comment by Dade916** [comment] 2019-04-19 09:30
> And one more: When rebuilding, and the pyluxcoretools.zip already exists, then the contents will not be updated, even if the source tree changes. So in order to apply patches, one has to force a rebuild / refresh, or remove the destination zip.

I'm on Linux and pyluxcoretools.zip is rebuilt when required (including when the file already exist).
