### ISSUE TITLE
LuxCore property number to string conversion is affected by locale

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/LuxCore#390] opened 2020-06-04 22:15 UTC
See issue LuxCoreRender/BlendLuxCore#477 

.blend file: https://github.com/LuxCoreRender/BlendLuxCore/files/4728948/PointLightBanding-BUG.zip

Steps to reproduce: 
Set Object or Material ID to -1.
Export/Write scene using LuxCore Filesaver as Text.
Load the scene file w/ LuxCoreUI

Error message from LuxCoreUI console:` RenderConfig loading error: bad lexical cast: source type value could not be interpreted as target`

OS: W10
Blender version: 2.83
LuxCore version: 2.4 beta2 (e15e45cef)
BlendLuxCore version: 2.4beta2 (8e6ca69)

**Comment by Theverat** [comment] 2020-06-05 08:40
@Dade916 Can we maybe use a custom number to string function that is not affected by the locale or C library?

**Comment by Dade916** [comment] 2020-06-05 10:30
But it is a bit strange, first of all, ID are unsigned int so -1 isn't a valid number, wasn't it used in BlendLuxCore to mark the default (random) assigned values ? I assume -1 should be exported as 2^32 = 4294967296.

Anyway @kintuX, are you sure the problem doesn't happen if if you use a value like 1000 ? I have the feeling it will be printed as "1,000".

**Comment by kintuX** [comment] 2020-06-05 11:08
> 
> 
> But it is a bit strange, first of all, ID are unsigned int so -1 isn't a valid number, wasn't it used in BlendLuxCore to mark the default (random) assigned values ? I assume -1 should be exported as 2^32 = 4294967296.
> 
> Anyway @kintuX, are you sure the problem doesn't happen if if you use a value like 1000 ? I have the feeling it will be printed as "1,000".

Yes, it does that. Prints with commas ",".
Replacing commas with periods ("," to ".") causes same issue & error report. 
Finally, it works fine without any symbols.

**Comment by Dade916** [comment] 2020-06-05 11:14
> @Dade916 Can we maybe use a custom number to string function that is not affected by the locale or C library?

But it should work anyway, I mean: I write and read the number with the same library, it should be able to read what it writes.

This may be some kind of side effect of some Blender setting. LuxCore standalone expect the number in "C" locale format (without "," or ".", as it should be) while LuxCore inside Blender starts to print numbers with ",". Blender must use a different locale. I will try to figure out a solution.

But it is problematic, all the "locale" idea is considered totally broken and useless. It is a global application setting and, as you see, it does a mess most of the times.

**Comment by kintuX** [comment] 2020-06-05 11:35
OK, I found a setting which causes this string conversion in Blender.

_Preference Editor > Interface > Translation > Language >_ **Automatic**
![BlenderPrefTransAuto-OK](https://user-images.githubusercontent.com/61623470/83871945-520c5f00-a731-11ea-8d22-a3ae00fdd4d2.jpg)

I had Language set to English. Now, with Automatic it doesn't do any conversion but keeps "original" string.

**Comment by Theverat** [comment] 2020-06-05 16:13
I think we can show a warning in the addon before rendering if the language is set to something other than "Automatic".

> But it should work anyway, I mean: I write and read the number with the same library, it should be able to read what it writes.
This may be some kind of side effect of some Blender setting. LuxCore standalone expect the number in "C" locale format (without "," or ".", as it should be) while LuxCore inside Blender starts to print numbers with ",". Blender must use a different locale. I will try to figure out a solution.

It really looks like this is a Blender problem, but it could be a problem when LuxCore is embedded in other applications, too. In my opinion it would be best to use a string conversion that doesn't depend on the locale.
These two might be interesting:
* https://stackoverflow.com/a/50405799
* https://en.cppreference.com/w/cpp/locale/num_put#Example

**Comment by Dade916** [comment] 2020-06-09 09:44
I pushed a tentative fix to the problem. It is, for the moment, limited to properties but it should fix the problem described in this issue.

@kintuX, can you try if it works now with the "automatic" setting ?

**Comment by Dade916** [comment] 2020-06-09 09:45
Duplicate of #103

**Comment by Dade916** [comment] 2020-06-11 10:19
I'm starting to have the feeling the problem may be in BlendLuxCore: @Theverat can you check if the material.id property is set as number and not as string ? I mean, if Blender gives the string "1,000" to BlendLuxCore and BlendLuxCore sets the property value as string, and not as a number, LuxCore will print the string "1,000".
In this case locale would be not affect how the string is handled inside LuxCore API.

@kintuX, are you just setting language to "English"  to replicate the problem ? Do you have default language/nation related system settings ?

**Comment by kintuX** [comment] 2020-06-11 18:12
@Dade916 Yes, I only switch in Blender from Automatic to English. I have Windows sytem using default language English US but with International Standard (metric units, date, CET time, EU number punctuation, € currency...)

I also suspect it's BlendLuxCore issue. BTW, I think @Theverat is away for a week.

**Comment by Dade916** [comment] 2020-06-11 18:15
I'm starting to think to a BlendLuxCore problem because it is quite strange to see this problem only with material.id while all other numbers seem to be printed fine.

**Comment by Theverat** [comment] 2020-06-25 12:52
> @Theverat can you check if the material.id property is set as number and not as string ? 

It is set as integer, as far as I can see.

**Comment by Dade916** [comment] 2020-06-27 09:54
I'm trying to replicate the problem, my Blender "Preference Editor > Interface > Translation > Language" was already set to "English" and it works fine. I assume there is something in @kintuX OS setting causing the problem.
If I can not replicate the problem, I can not fix it.

**Comment by kintuX** [comment] 2020-08-04 12:13
Here are another strange cases, files showing same issues, but aren't any commas present (already replaced w/ periods)...
there's also [ongoing chat on Discord](https://discord.com/channels/476391564948668426/476391764798865409/740171434047045694)
[lux file saver commaFix.zip](https://github.com/LuxCoreRender/LuxCore/files/5021977/lux.file.saver.commaFix.zip)

**Comment by Dade916** [comment] 2020-09-25 10:30
As far as I know, this problem as been fixed (the relative discussion was on our forum).

**Closed by Dade916** 2020-09-25 10:30 UTC
Labels: bug
