### ISSUE TITLE
please update cycles nodes converter

### ISSUE THREAD

**Issue by hizih** [LuxCoreRender/LuxCore#489] opened 2020-12-23 11:30 UTC
luxcore not converting cycles glass materials (emission bsdf, add shader, glass bsdf). please update cycles nodes converter

**Comment by Dade916** [comment] 2020-12-25 10:08
This issue is a duplicate of https://github.com/LuxCoreRender/BlendLuxCore/issues/272 and any related discussion should continue there.

**Closed by Dade916** 2020-12-25 10:08 UTC
Labels: duplicate
