### ISSUE TITLE
Please re-open issue #160

### ISSUE THREAD

**Issue by happysmash27** [LuxCoreRender/LuxCore#472] opened 2020-11-18 22:31 UTC
I have been wanting nearest neighbour sampling in LuxCoreRender for years now, and it still hasn't been added. All I have is a workaround of resizing the textures, which is very inefficient, results in UVs not being as precise as I want them to be (many textures go over the lines), and currently, is even more of an issue, since it means that I cannot use the same assets for renders in Blender and exporting to external programs where optimisation is more important. Now that I have time, I would like to implement a fix for this myself, but I have lots I need to learn about how LuxCoreRender works, and the issue I created for this, issue #160, has been closed, even though it has not been fixed yet. I would like to request that is re-opened, so that I have a good place to ask questions about how LuxCoreRender works so I can implement this fix, so that I can reference it in a future pull request, and so that the issue reflects, that **this has not been fixed yet**. I've been using a mediocre workaround for years, and I am very tired of it.

**Comment by Dade916** [comment] 2020-11-19 09:52
Duplicate of #160 .

Note: it is not a fix, it is an enchantment request so it may be added or not.

**Closed by Dade916** 2020-11-19 09:52 UTC
Labels: question
