### ISSUE TITLE
Is there planned BidirPT with GPU computing?

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/LuxCore#518] opened 2021-03-25 12:23 UTC
Hi. Just would like to know is there planned something like this or no?
Like this:
https://www.google.com/search?client=lightning&ie=UTF-8&oe=UTF-8&q=gpu+bidirectional+path+tracing

**Comment by Theverat** [comment] 2021-03-25 13:54
Duplicate of #85

**Closed by Theverat** 2021-03-25 13:54 UTC
