### ISSUE TITLE
BlendLuxCore 2.4 not working on Big Sur (OCL issue) 

### ISSUE THREAD

**Issue by thebuza** [LuxCoreRender/LuxCore#468] opened 2020-11-13 11:51 UTC
Hope you guys can help here and it'll be an easy fix. So the 2.4 version doesn't work on Big Sur, either on CPU and GPU because of the OpenCL in image pipeline. If tuned off - it works. 

![Zrzut ekranu 2020-11-13 o 12 06 07](https://user-images.githubusercontent.com/45789626/99069057-ecf54900-25ad-11eb-9313-94795421ff02.jpg)

However, to show you that it is not an OS issue - I can run 2.3 on CPU and GPU without any problem. Kernel compilation goes fine.

Video from screen 2.4 with OCL error:
https://streamable.com/8fx2od

Video from screen 2.3:
https://streamable.com/x0skyp

**Comment by jamespa16** [comment] 2020-11-13 12:47
I have a Radeon VII which does work with latest LuxCore + Big Sur - this particular issue is probably related to driver changes for the Neptune (GCN 1.0) architecture specifically.

**Comment by Ahr0n** [comment] 2020-11-13 12:56
Hm, okay. Is there anything I can do with it? 

But then why the 2.3 works fine? Isn't that an OCL issue in LuxCore?

**Comment by u3dreal** [comment] 2020-11-13 14:28
Does it work on Catalina ? I remember you had many Problems there too.
For me Catalina and RX 5700 work very fast.

**Comment by u3dreal** [comment] 2020-11-13 14:29
> I have a Radeon VII which does work with latest LuxCore + Big Sur - this particular issue is probably related to driver changes for the Neptune (GCN 1.0) architecture specifically.

Great to know.

**Comment by Ahr0n** [comment] 2020-11-13 14:31
On Mojave and Catalina it worked fine. But now on Big Sur it is not good. @u3dreal take also in mind that 2.3 works well on Big Sur. OCL GPU - perfect. Don't really know what's wrong with 2.4 and 2.5 (checked also that).

**Comment by Ahr0n** [comment] 2020-11-13 14:34
Here's the exact error I have: OpenCL driver API error (code -30, file:/Users/runner/work/1/s/src/luxrays/utils/ocl.cpp, line: 366): CLINVALIDVALUE

Don't know what's the runner directory, I can't go there, looks like it's hidden and don't know how to go there

**Comment by u3dreal** [comment] 2020-11-13 14:38
Which GPU fo you have ?

**Comment by Ahr0n** [comment] 2020-11-13 14:39
AMD R9 M290X (Neptune arch. GCN 1.0)

**Comment by u3dreal** [comment] 2020-11-13 14:45
Sorry i have no way of testing that. It seems to be a driver problem.

**Comment by Ahr0n** [comment] 2020-11-13 14:47
So why the 2.3 works and 2.4 doesn't work? Please see my screen recordings of both of them. Maybe comparing the code would help in bug fixing?

**Comment by u3dreal** [comment] 2020-11-13 14:52
As far as i can tell the error gets invoked in line 366. The Error is from the driver itself.
2.4/5 kernels are way more complex then 2.3. It's not the same. Even Intel cards work with 2.3.

**Comment by Ahr0n** [comment] 2020-11-13 14:58
Okay, do you think it's good to report that to Apple and are there any chances they'll fix it? If yes do you know how can I report that to them?

**Comment by jamespa16** [comment] 2020-11-13 17:12
there is no chance they fix an OpenCL issue. it is officially depreciated which means it's your problem if it's broken. and since the drivers aren't open source, you have to either a) work around it or b) move to Metal. in this case, moving to Metal would be the best thing to do, though it is unlikely to happen anytime soon.

**Comment by u3dreal** [comment] 2020-12-30 18:28
I was able to reproduce this issue now finally after updating to 11.1. Have no cure though. So it seems to be related to latest AMD drivers.

**Comment by u3dreal** [comment] 2021-02-05 13:36
Problem seems to be solved in BigSur 11.2 . Make sure to delete the old kernel cache in HOME/Luxcorerender.org

**Closed** 2021-05-15 12:21 UTC

**Comment by dani3315** [comment] 2021-09-17 12:47
Problem is not solved. Please see my comments here:

https://github.com/LuxCoreRender/BlendLuxCore/issues/726#issuecomment-920643121

https://github.com/LuxCoreRender/BlendLuxCore/issues/726#issuecomment-921675885
<img width="1364" alt="Screen Shot 2021-09-17 at 12 36 56 PM" src="https://user-images.githubusercontent.com/38330000/133784762-304b1734-b4fb-48bc-be1c-28ef5a20938b.png">
