### ISSUE TITLE
LUT loader for camera tonemapper

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#365] opened 2020-05-11 13:16 UTC
Loading .CUBE or possibly other formats of lut files into camera.

Important to have also a control over mixing/blending in % so that some more agressive configs can be controlled

**Comment by lacilaci** [comment] 2020-05-11 13:24
I might just be stupid, but i don't see a "post bounty" anywhere...

**Comment by Theverat** [comment] 2020-05-11 13:27
The bountysource website is having outages for some weeks now, it's probably caused by that.

**Comment by Dade916** [comment] 2020-05-11 23:22
This is a duplicate of #81.

**Comment by Dade916** [comment] 2020-05-11 23:22
I assume we can continue the discussion on the original issue.

**Closed by Dade916** 2020-05-11 23:22 UTC
